# Generated by Django 4.2.3 on 2023-12-23 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=64)),
                ('lname', models.CharField(max_length=64)),
                ('birthdate', models.DateTimeField()),
                ('startdate', models.DateTimeField()),
                ('department', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=64)),
                ('education', models.TextField()),
                ('permit', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.TextField()),
                ('time_off', models.IntegerField(null=True)),
                ('leave_type', models.IntegerField(null=True)),
                ('leave_duration', models.IntegerField(null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.emp')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.FloatField()),
                ('benefit', models.IntegerField(null=True)),
                ('tax', models.FloatField()),
                ('bonus', models.FloatField(null=True)),
                ('net', models.FloatField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.emp')),
            ],
        ),
        migrations.CreateModel(
            name='Bank_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_name', models.CharField(max_length=255)),
                ('bank_company_name', models.TextField()),
                ('bank_account_number', models.TextField()),
                ('bank_IBAN', models.TextField()),
                ('bank_account_type', models.CharField(max_length=64)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.emp')),
            ],
        ),
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('shift', models.TextField()),
                ('absent', models.ManyToManyField(related_name='absentee', to='HR.emp')),
                ('present', models.ManyToManyField(related_name='presentee', to='HR.emp')),
            ],
        ),
    ]
