# Generated by Django 4.2.3 on 2023-12-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='email',
            field=models.CharField(default='ex@g.c', max_length=64),
        ),
        migrations.AlterField(
            model_name='emp',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='emp',
            name='startdate',
            field=models.DateField(),
        ),
    ]
