# Generated by Django 4.2.3 on 2023-12-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_job_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_post',
            old_name='postion',
            new_name='position',
        ),
    ]
