# Generated by Django 4.2.3 on 2023-12-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_applicant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
