# Generated by Django 4.2.3 on 2023-12-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='file',
            field=models.TextField(null=True),
        ),
    ]
