# Generated by Django 4.2.3 on 2023-12-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0009_applicant_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_details',
            name='bank_IBAN',
            field=models.TextField(null=True),
        ),
    ]
