# Generated by Django 4.2.3 on 2023-12-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0010_alter_bank_details_bank_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='retirement',
            field=models.IntegerField(null=True),
        ),
    ]
