# Generated by Django 4.2.3 on 2023-12-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0012_remove_payroll_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='net',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='benefit',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
