# Generated by Django 4.2.3 on 2023-12-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0013_remove_payroll_net_alter_payroll_benefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('lecture', models.TextField(null=True)),
                ('assess', models.TextField(null=True)),
                ('req_no', models.IntegerField()),
            ],
        ),
    ]
