# Generated by Django 4.2.3 on 2023-12-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0016_remove_attend_shift_attend_open_emp_leave_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attend',
            name='date',
            field=models.DateField(),
        ),
    ]
