# Generated by Django 4.2.3 on 2023-12-27 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0017_alter_attend_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('req_type', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255, null=True)),
                ('link', models.TextField(null=True)),
                ('answer', models.TextField(null=True)),
                ('open', models.IntegerField(default=1)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.emp')),
            ],
        ),
    ]
